# PostgreSQL. Versions 9.3 and up are supported.
# Configure Using Gemfile: gem "pg"

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  database: habit_tracker
  username: postgres
  password: mypassword
  host: localhost
  port: 5432

test:
  <<: *default
  # Standard Rails naming convention, but you can also create a "habit_tracker_test" DB if you like.
  database: habit_tracker_test
  username: postgres
  # password: "mysecretpassword"
  host: localhost
  port: 5432

production:
  primary: &primary_production
    <<: *default
    database: habit_tracker_production
    username: habit_tracker
    # password: <%= ENV["HABIT_TRACKER_DATABASE_PASSWORD"] %>

  cache:
    <<: *primary_production
    database: habit_tracker_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: habit_tracker_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: habit_tracker_production_cable
    migrations_paths: db/cable_migrate
